create or replace FUNCTION FN_GET_ORDER_NO 
    RETURN CHAR
IS 
    CODE CHAR(12);
    BASE_CODE CHAR(8);
    MAX_NUM NUMBER;
BEGIN 
    SELECT  TO_CHAR(SYSDATE, 'YYYYMMDD') INTO BASE_CODE
    FROM    DUAL;
    
    SELECT  BASE_CODE || SUBSTR(NVL(MAX(SUBSTR(ORDER_NUM, 9, 4)), 0) + 10001, -4)INTO CODE
    FROM    ORDER_TB
    WHERE   SUBSTR(ORDER_NUM, 1, 8) = TO_CHAR(SYSDATE, 'YYYYMMDD');

    RETURN CODE;
END;