CREATE OR REPLACE FUNCTION SUMMARY_AMOUNT(INPUT_ID VARCHAR)
    RETURN NUMBER
IS
    RESULT_DATA VARCHAR2(100);
BEGIN
    SELECT  NVL(SUM(A.PRODUCT_QTY * A.PRODUCT_PRICE * (100 - D.GRADE_DC_RATE)/100),0) INTO RESULT_DATA
    FROM    ORDER_DETAIL A
    JOIN    ORDER_TB B ON A.ORDER_NUM = B.ORDER_NUM
    JOIN    MEMBER C ON B.MEMBER_ID = C.MEMBER_ID
    JOIN    GRADE D ON C.GRADE_NUM = D.GRADE_NUM
    WHERE   B.CDT BETWEEN ADD_MONTHS(SYSDATE, -3) AND SYSDATE
    AND     B.MEMBER_ID = INPUT_ID
    AND     B.STATUS_NUM = 2;
RETURN RESULT_DATA;
END;